version: '3.8'

services:
  # C++ Physics Engine
  cpp-physics:
    build:
      context: ./src/cpp_physics
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    networks:
      - tetris_network

  # Python Game Server
  python-server:
    build:
      context: ./src/python_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO

  # Python Game Logic
  python-logic:
    build:
      context: ./src/python_logic
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    depends_on:
      - cpp-physics

  # TypeScript Client
  typescript-client:
    build:
      context: ./src/typescript_client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    networks:
      - tetris_network

  # Go Development Tools
  go-tools:
    build:
      context: ./src/go_tools
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - LOG_LEVEL=INFO
    networks:
      - tetris_network

  # Python Analytics
  python-analytics:
    build:
      context: ./src/python_analytics
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    networks:
      - tetris_network

  # Python AI
  python-ai:
    build:
      context: ./src/python_ai
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    networks:
      - tetris_network

  # PostgreSQL
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=tetris_analytics
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tetris_network

networks:
  tetris_network:
    driver: bridge

volumes:
  postgres_data:
