[network]
host = "127.0.0.1"
port = 8080
max_message_size = 1048576
connection_timeout = 60
enable_cors = true
cors_allowed_origins = ["*"]
enable_ssl = false
ssl_cert_path = "cert.pem"
ssl_key_path = "key.pem"

[session]
session_ttl = 3600
cleanup_interval = 300
max_sessions = 1000
enable_heartbeat = true
heartbeat_interval = 30
inactivity_timeout = 300

[game]
max_players = 4
field_height = 20
field_width = 10
update_interval_ms = 16
debug_mode = false
resources_path = "resources"

[physics]
library_path = "lib/libtetris_physics.so"
gravity_x = 0.0
gravity_y = -9.8
iterations = 10
fixed_time_step = 0.016666667
auto_simulation = true 